TAGS = {
    "06": "Object Identifier (OID)",
    "41": "Country code and national data",
    "42": "Issuer Identification Number (IIN)",
    "43": "Card service data",
    "44": "Initial access data",
    "45": "Card issuer's data",
    "46": "Pre-issuing data",
    "47": "Card capabilities",
    "48": "Status information",
    "4D": "Extended header list",
    "4F": "Application Identifier (ADF Name)",
    "50": "Application Label",
    "51": "Path",
    "52": "Command to perform",
    "53": "Discretionary data, discretionary template",
    "56": "Track 1 Equivalent Data",
    "57": "Track 2 Equivalent Data",
    "58": "Track 3 Equivalent Data",
    "59": "Card expiration date",
    "5A": "Application Primary Account Number (PAN)",
    "5B": "Name of an individual",
    "5C": "Tag list",
    "5E": "Proprietary login data",
    "5F20": "Cardholder Name",
    "5F21": "Track 1, identical to the data coded",
    "5F22": "Track 2, identical to the data coded",
    "5F23": "Track 3, identical to the data coded",
    "5F24": "Application Expiration Date (YYMMDD)",
    "5F25": "Application Effective Date (YYMMDD)",
    "5F26": "Date, Card Effective",
    "5F27": "Interchange control",
    "5F28": "Issuer Country Code",
    "5F29": "Interchange profile",
    "5F2A": "Transaction Currency Code",
    "5F2B": "Date of birth",
    "5F2C": "Cardholder nationality",
    "5F2D": "Language Preference",
    "5F2E": "Cardholder biometric data",
    "5F2F": "PIN usage policy",
    "5F30": "Service Code",
    "5F32": "Transaction counter",
    "5F33": "Date, Transaction",
    "5F34": "Application Primary Account Number (PAN) Sequence Number (PSN)",
    "5F35": "Sex (ISO 5218)",
    "5F36": "Transaction Currency Exponent",
    "5F37": "Static internal authentication (one-step)",
    "5F38": "Static internal authentication - first associated data",
    "5F39": "Static internal authentication - second associated data",
    "5F3A": "Dynamic internal authentication",
    "5F3B": "Dynamic external authentication",
    "5F3C": "Transaction Reference Currency Code",
    "5F3D": "Transaction Reference Currency Exponent",
    "5F40": "Cardholder portrait image",
    "5F41": "Element list",
    "5F42": "Address",
    "5F43": "Cardholder handwritten signature image",
    "5F44": "Application image",
    "5F45": "Display message",
    "5F46": "Timer",
    "5F47": "Message reference",
    "5F48": "Cardholder private key",
    "5F49": "Cardholder public key",
    "5F4A": "Public key of certification authority",
    "5F4C": "Certificate holder authorization",
    "5F4D": "Integrated circuit manufacturer identifier",
    "5F4E": "Certificate content",
    "5F50": "Issuer Uniform resource locator (URL)",
    "5F53": "International Bank Account Number (IBAN)",
    "5F54": "Bank Identifier Code (BIC)",
    "5F55": "Issuer Country Code (alpha2 format)",
    "5F56": "Issuer Country Code (alpha3 format)",
    "5F57": "Account Type",
    "60": "Template, Dynamic Authentication",
    "6080": "Commitment",
    "6081": "Challenge",
    "6082": "Response",
    "6083": "Committed challenge",
    "6084": "Authentication code",
    "6085": "Exponential",
    "60A0": "Template, Identification data",
    "61": "Application Template",
    "62": "File Control Parameters (FCP) Template",
    "6280": "Number of data bytes in the file, excluding structural information",
    "6281": "Number of data bytes in the file, including structural information if any",
    "6282": "File descriptor byte",
    "6283": "File identifier",
    "6284": "DF name",
    "6285": "Proprietary information, primitive encoding",
    "6286": "Security attribute in proprietary format",
    "6287": "Identifier of an EF containing an extension of the file control information",
    "6288": "Short EF identifier",
    "628A": "Life cycle status byte (LCS)",
    "628B": "Security attribute referencing the expanded format",
    "628C": "Security attribute in compact format",
    "628D": "Identifier of an EF containing security environment templates",
    "62A0": "Template, Security attribute for data objects",
    "62A1": "Template, Security attribute for physical interfaces",
    "62A2": "One or more pairs of data objects, short EF identifier (tag 88) - absolute or relative path (tag 51)",
    "62A5": "Proprietary information, constructed encoding",
    "62AB": "Security attribute in expanded format",
    "62AC": "Identifier of a cryptographic mechanism",
    "63": "Wrapper",
    "64": "Template, File Management Data (FMD)",
    "65": "Cardholder related data",
    "66": "Template, Card data",
    "67": "Template, Authentication data",
    "68": "Special user requirements",
    "6A": "Template, Login",
    "6A80": "Qualifier",
    "6A81": "Telephone Number",
    "6A82": "Text",
    "6A83": "Delay indicators, for detecting an end of message",
    "6A84": "Delay indicators, for detecting an absence of response",
    "6B": "Template, Qualified name",
    "6B06": "Qualified name",
    "6B80": "Name",
    "6BA0": "Name",
    "6C": "Template, Cardholder image",
    "6D": "Template, Application image",
    "6E": "Application related data",
    "6F": "File Control Information (FCI) Template",
    "6FA5": "Template, FCI A5",
    "70": "READ RECORD Response Message Template",
    "71": "Issuer Script Template 1",
    "7186": "Issuer Script Command",
    "719F18": "Issuer Script Identifier",
    "72": "Issuer Script Template 2",
    "73": "Directory Discretionary Template",
    "77": "Response Message Template Format 2",
    "78": "Compatible Tag Allocation Authority",
    "79": "Coexistent Tag Allocation Authority",
    "7A": "Template, Security Support (SS)",
    "7A80": "Card session counter",
    "7A81": "Session identifier",
    "7A82": "File selection counter",
    "7A83": "File selection counter",
    "7A84": "File selection counter",
    "7A85": "File selection counter",
    "7A86": "File selection counter",
    "7A87": "File selection counter",
    "7A88": "File selection counter",
    "7A89": "File selection counter",
    "7A8A": "File selection counter",
    "7A8B": "File selection counter",
    "7A8C": "File selection counter",
    "7A8D": "File selection counter",
    "7A8E": "File selection counter",
    "7A93": "Digital signature counter",
    "7B": "Template, Security Environment (SE)",
    "7B80": "SEID byte, mandatory",
    "7B8A": "LCS byte, optional",
    "7BAC": "Cryptographic mechanism identifier template, optional",
    "7BA4": "Control reference template (CRT)",
    "7BAA": "Control reference template (CRT)",
    "7BB4": "Control reference template (CRT)",
    "7BB6": "Control reference template (CRT)",
    "7BB8": "Control reference template (CRT)",
    "7D": "Template, Secure Messaging (SM)",
    "7D80": "Plain value not coded in BER-TLV",
    "7D81": "Plain value not coded in BER-TLV",
    "7D82": "Cryptogram (plain value coded in BER-TLV and including secure messaging data objects)",
    "7D83": "Cryptogram (plain value coded in BER-TLV and including secure messaging data objects)",
    "7D84": "Cryptogram (plain value coded in BER-TLV, but not including secure messaging data objects)",
    "7D85": "Cryptogram (plain value coded in BER-TLV, but not including secure messaging data objects)",
    "7D86": "Padding-content indicator byte followed by cryptogram (plain value not coded in BER-TLV)",
    "7D87": "Padding-content indicator byte followed by cryptogram (plain value not coded in BER-TLV)",
    "7D8E": "Cryptographic checksum (at least four bytes)",
    "7D90": "Hash-code",
    "7D91": "Hash-code",
    "7D92": "Certificate (not BER-TLV coded data)",
    "7D93": "Certificate (not BER-TLV coded data)",
    "7D94": "Security environment identifier",
    "7D95": "Security environment identifier",
    "7D96": "Number Le in the unsecured command APDU (one or two bytes)",
    "7D97": "Number Le in the unsecured command APDU (one or two bytes)",
    "7D99": "Processing status of the secured response APDU (new SW1-SW2, two bytes)",
    "7D9A": "Input data element for the computation of a digital signature (the value field is signed)",
    "7D9B": "Input data element for the computation of a digital signature (the value field is signed)",
    "7D9C": "Public key",
    "7D9D": "Public key",
    "7D9E": "Digital signature",
    "7DA0": "Input template for the computation of a hash-code (the template is hashed)",
    "7DA1": "Input template for the computation of a hash-code (the template is hashed)",
    "7DA2": "Input template for the verification of a cryptographic checksum (the template is integrated)",
    "7DA4": "Control reference template for authentication (AT)",
    "7DA5": "Control reference template for authentication (AT)",
    "7DA8": "Input template for the verification of a digital signature (the template is signed)",
    "7DAA": "Template, Control reference for hash-code (HT)",
    "7DAB": "Template, Control reference for hash-code (HT)",
    "7DAC": "Input template for the computation of a digital signature (the concatenated value fields are signed)",
    "7DAD": "Input template for the computation of a digital signature (the concatenated value fields are signed)",
    "7DAE": "Input template for the computation of a certificate (the concatenated value fields are certified)",
    "7DAF": "Input template for the computation of a certificate (the concatenated value fields are certified)",
    "7DB0": "Plain value coded in BER-TLV and including secure messaging data objects",
    "7DB1": "Plain value coded in BER-TLV and including secure messaging data objects",
    "7DB2": "Plain value coded in BER-TLV, but not including secure messaging data objects",
    "7DB3": "Plain value coded in BER-TLV, but not including secure messaging data objects",
    "7DB4": "Control reference template for cryptographic checksum (CCT)",
    "7DB5": "Control reference template for cryptographic checksum (CCT)",
    "7DB6": "Control reference template for digital signature (DST)",
    "7DB7": "Control reference template for digital signature (DST)",
    "7DB8": "Control reference template for confidentiality (CT)",
    "7DB9": "Control reference template for confidentiality (CT)",
    "7DBA": "Response descriptor template",
    "7DBB": "Response descriptor template",
    "7DBC": "Input template for the computation of a digital signature (the template is signed)",
    "7DBD": "Input template for the computation of a digital signature (the template is signed)",
    "7DBE": "Input template for the verification of a certificate (the template is certified)",
    "7E": "Template, Nesting Interindustry data objects",
    "7F20": "Display control template",
    "7F21": "Cardholder certificate",
    "7F2E": "Biometric data template",
    "7F49": "Template, Cardholder public key",
    "7F4980": "Algorithm reference as used in control reference data objects for secure messaging",
    "7F4981": "RSA Modulus",
    "7F4982": "RSA Public exponent",
    "7F4983": "DSA Basis",
    "7F4984": "DSA Public key",
    "7F4985": "ECDSA Order",
    "7F4986": "ECDSA Public key",
    "7F4C": "Template, Certificate Holder Authorization",
    "7F4E": "Certificate Body",
    "7F4E42": "Certificate Authority Reference",
    "7F4E65": "Certificate Extensions",
    "7F60": "Template, Biometric information",
    "80": "Response Message Template Format 1",
    "81": "Amount, Authorised (Binary)",
    "82": "Application Interchange Profile (AIP)",
    "83": "Command Template",
    "84": "Dedicated File (DF) Name",
    "86": "Issuer Script Command",
    "87": "Application Priority Indicator",
    "88": "Short File Identifier (SFI)",
    "89": "Authorisation Code",
    "8A": "Authorisation Response Code (ARC)",
    "8C": "Card Risk Management Data Object List 1 (CDOL1)",
    "8D": "Card Risk Management Data Object List 2 (CDOL2)",
    "8E": "Cardholder Verification Method (CVM) List",
    "8F": "Certification Authority Public Key Index (PKI)",
    "90": "Issuer Public Key Certificate",
    "91": "Issuer Authentication Data",
    "92": "Issuer Public Key Remainder",
    "93": "Signed Static Application Data (SAD)",
    "94": "Application File Locator (AFL)",
    "95": "Terminal Verification Results (TVR)",
    "97": "Transaction Certificate Data Object List (TDOL)",
    "98": "Transaction Certificate (TC) Hash Value",
    "99": "Transaction Personal Identification Number (PIN) Data",
    "9A": "Transaction Date (YYMMDD)",
    "9B": "Transaction Status Information (TSI)",
    "9C": "Transaction Type",
    "9D": "Directory Definition File (DDF) Name",
    "9F01": "Acquirer Identifier",
    "9F02": "Amount, Authorised (Numeric)",
    "9F03": "Amount, Other (Numeric)",
    "9F04": "Amount, Other (Binary)",
    "9F05": "Application Discretionary Data",
    "9F06": "Application Identifier (AID), Terminal",
    "9F07": "Application Usage Control (AUC)",
    "9F08": "Application Version Number",
    "9F09": "Application Version Number",
    "9F0A": "Application Selection Registered Proprietary Data",
    "9F0B": "Cardholder Name - Extended",
    "9F0D": "Issuer Action Code - Default",
    "9F0E": "Issuer Action Code - Denial",
    "9F0F": "Issuer Action Code - Online",
    "9F10": "Issuer Application Data (IAD)",
    "9F11": "Issuer Code Table Index",
    "9F12": "Application Preferred Name",
    "9F13": "Last Online Application Transaction Counter (ATC) Register",
    "9F14": "Lower Consecutive Offline Limit (LCOL)",
    "9F15": "Merchant Category Code (MCC)",
    "9F16": "Merchant Identifier",
    "9F17": "Personal Identification Number (PIN) Try Counter",
    "9F18": "Issuer Script Identifier",
    "9F19": "Token Requestor ID",
    "9F1A": "Terminal Country Code",
    "9F1B": "Terminal Floor Limit",
    "9F1C": "Terminal Identification",
    "9F1D": "Terminal Risk Management Data",
    "9F1E": "Interface Device (IFD) Serial Number",
    "9F1F": "Track 1 Discretionary Data",
    "9F20": "Track 2 Discretionary Data",
    "9F21": "Transaction Time",
    "9F22": "Public Key Index, Certification Authority, Terminal",
    "9F23": "Upper Consecutive Offline Limit (UCOL)",
    "9F24": "Payment Account Reference (PAR)",
    "9F26": "Application Cryptogram (AC)",
    "9F27": "Cryptogram Information Data (CID)",
    "9F29": "Extended Selection",
    "9F2A": "Kernel Identifier",
    "9F2D": "Integrated Circuit Card (ICC) PIN Encipherment Public Key Certificate",
    "9F2E": "Integrated Circuit Card (ICC) PIN Encipherment Public Key Exponent",
    "9F2F": "Integrated Circuit Card (ICC) PIN Encipherment Public Key Remainder",
    "9F32": "Issuer Public Key Exponent",
    "9F33": "Terminal Capabilities",
    "9F34": "Cardholder Verification Method (CVM) Results",
    "9F35": "Terminal Type",
    "9F36": "Application Transaction Counter (ATC)",
    "9F37": "Unpredictable Number (UN)",
    "9F38": "Processing Options Data Object List (PDOL)",
    "9F39": "Point-of-Service (POS) Entry Mode",
    "9F3A": "Amount, Reference Currency (Binary)",
    "9F3B": "Currency Code, Application Reference",
    "9F3C": "Currency Code, Transaction Reference",
    "9F3D": "Currency Exponent, Transaction Reference",
    "9F40": "Additional Terminal Capabilities (ATC)",
    "9F41": "Transaction Sequence Counter",
    "9F42": "Currency Code, Application",
    "9F43": "Currency Exponent, Application Reference",
    "9F44": "Currency Exponent, Application",
    "9F45": "Data Authentication Code",
    "9F46": "Integrated Circuit Card (ICC) Public Key Certificate",
    "9F47": "Integrated Circuit Card (ICC) Public Key Exponent",
    "9F48": "Integrated Circuit Card (ICC) Public Key Remainder",
    "9F49": "Dynamic Data Authentication Data Object List (DDOL)",
    "9F4A": "Static Data Authentication Tag List (SDA)",
    "9F4B": "Signed Dynamic Application Data (SDAD)",
    "9F4C": "ICC Dynamic Number",
    "9F4D": "Log Entry",
    "9F4E": "Merchant Name and Location",
    "9F4F": "Log Format",
    "9F50": "Cardholder Verification Status",
    "9F51": "Application Currency Code",
    "9F52": "Card Verification Results (CVR)",
    "9F53": "Consecutive Transaction Counter International Limit (CTCIL)",
    "9F54": "Cumulative Total Transaction Amount Limit (CTTAL)",
    "9F55": "Geographic Indicator",
    "9F56": "Issuer Authentication Indicator",
    "9F57": "Issuer Country Code",
    "9F58": "Consecutive Transaction Counter Limit (CTCL)",
    "9F59": "Consecutive Transaction Counter Upper Limit (CTCUL)",
    "9F5A": "Application Program Identifier (Program ID)",
    "9F5B": "Issuer Script Results",
    "9F5C": "Cumulative Total Transaction Amount Upper Limit (CTTAUL)",
    "9F5D": "Available Offline Spending Amount (AOSA)",
    "9F5E": "Consecutive Transaction International Upper Limit (CTIUL)",
    "9F5F": "DS Slot Availability",
    "9F60": "CVC3 (Track1)",
    "9F61": "CVC3 (Track2)",
    "9F62": "PCVC3 (Track1)",
    "9F63": "Offline Counter Initial Value",
    "9F64": "NATC (Track1)",
    "9F65": "PCVC3 (Track2)",
    "9F66": "Terminal Transaction Qualifiers (TTQ)",
    "9F67": "MSD Offset",
    "9F68": "Card Additional Processes",
    "9F69": "Card Authentication Related Data",
    "9F6A": "Unpredictable Number (Numeric)",
    "9F6B": "Card CVM Limit",
    "9F6C": "Card Transaction Qualifiers (CTQ)",
    "9F6D": "VLP Reset Threshold",
    "9F6E": "Third Party Data / Form Factor Indicator",
    "9F6F": "DS Slot Management Control",
    "9F70": "Protected Data Envelope 1",
    "9F71": "Protected Data Envelope 2",
    "9F72": "Protected Data Envelope 3",
    "9F73": "Protected Data Envelope 4",
    "9F74": "Protected Data Envelope 5",
    "9F75": "Unprotected Data Envelope 1",
    "9F76": "Unprotected Data Envelope 2",
    "9F77": "Unprotected Data Envelope 3",
    "9F78": "Unprotected Data Envelope 4",
    "9F79": "Unprotected Data Envelope 5",
    "9F7A": "VLP Terminal Support Indicator",
    "9F7B": "VLP Terminal Transaction Limit",
    "9F7C": "Customer Exclusive Data (CED)",
    "9F7D": "DS Summary 1",
    "9F7E": "Mobile Support Indicator",
    "9F7F": "DS Unpredictable Number",
    "A5": "File Control Information (FCI) Proprietary Template",
    "BF0C": "File Control Information (FCI) Issuer Discretionary Data",
    "BF50": "Visa Fleet - CDO",
    "BF60": "Integrated Data Storage Record Update Template",
    "C3": "Card issuer action code -decline",
    "C4": "Card issuer action code -default",
    "C5": "Card issuer action code online",
    "C6": "PIN Try Limit",
    "C7": "CDOL 1 Related Data Length",
    "C8": "Card risk management country code",
    "C9": "Card risk management currency code",
    "CA": "Lower cummulative offline transaction amount",
    "CB": "Upper cumulative offline transaction amount",
    "CD": "Card Issuer Action Code (PayPass) - Default",
    "CE": "Card Issuer Action Code (PayPass) - Online",
    "CF": "Card Issuer Action Code (PayPass) - Decline",
    "D1": "Currency conversion table",
    "D2": "Integrated Data Storage Directory (IDSD)",
    "D3": "Additional check table",
    "D5": "Application Control",
    "D6": "Default ARPC response code",
    "D7": "Application Control (PayPass)",
    "D8": "AIP (PayPass)",
    "D9": "AFL (PayPass)",
    "DA": "Static CVC3-TRACK1",
    "DB": "Static CVC3-TRACK2",
    "DC": "IVCVC3-TRACK1",
    "DD": "IVCVC3-TRACK2"
}
